#!/bin/sh

WALL=itmot
HOST=localhost
PORT=1234

#SENDER=$1
#RECEIVER=$2
#AMOUNT=$3

PARAMFILE=/tmp/wall-$$
GETTEXT="gettext -d itmo_ui"

if [ -r ~/.wall.conf ]
then
	. ~/.wall.conf
elif [ -r /etc/wall.conf ]
then
	. /etc/wall.conf
fi

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

help () {
        echo "Usage: $0 [ host [port] | --help ]"
}

end () {
	rm -f $PARAMFILE
	exit
}

if [ $# -eq 1 ]
then
        if [ $1 -eq '--help' ]
        then
                help
                exit -1
        else
                HOST=$1
        fi
elif [ $# -eq 2 ]
then
        PORT=$2
fi

if [ $# -ge 1 -o `basename $0` = 'itmo_ui' ]
then
	if [ $HOST -a $PORT ]
	then
	        WALL="nc $HOST $PORT"
	else
		echo "You must set HOST and PORT"
		exit -2
	fi
fi

while true
do
	$DIALOG --title "Wallet" --inputbox "`gettext \"Insert SENDER account:\"`" 8 35 2> $PARAMFILE
	SENDER=$(cat $PARAMFILE)

	$DIALOG --title "Wallet" --inputbox "`gettext \"Insert RECEIVER account:\"`" 8 35 2> $PARAMFILE
	RECEIVER=$(cat $PARAMFILE)

	$DIALOG --title "Wallet" --inputbox "`gettext \"Insert AMOUNT to transfer Ethers:\"`" 8 35 2> $PARAMFILE
	AMOUNT=$(cat $PARAMFILE)

	TRANSACTION=$(./itmot -a $SENDER $RECEIVER $AMOUNT)
	echo $TRANSACTION

	MSG="`$GETTEXT \"Transaction ID is:\"`"
	MSG+="$TRANSACTION"
	$DIALOG --title "`$GETTEXT \"TRANSACTION number is:\"`" --msgbox "$TRANSACTION" 10 40
	end

	MSG="`$GETTEXT \"Do you want to make another transaction?\"`"
	$DIALOG --title "$NAME" --yesno "$MSG" 10 50 || exit
done
