#!/bin/sh

WALL=itmot
HOST=localhost
PORT=1234

FILE1=/tmp/wall1-$$
FILE2=/tmp/wall2-$$
ERROR=/tmp/wall-err-$$

if [ -r ~/.wall.conf ]
then
	. ~/.wall.conf
elif [ -r /etc/wall.conf ]
then
	. /etc/wall.conf
fi

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

help () {
        echo "Usage: $0 [ host [port] | --help ]"
}

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

if [ $# -eq 1 ]
then
        if [ $1 -eq '--help' ]
        then
                help
                exit -1
        else
                HOST=$1
        fi
elif [ $# -eq 2 ]
then
        PORT=$2
fi

if [ $# -ge 1 -o `basename $0` = 'itmo_ui' ]
then
	if [ $HOST -a $PORT ]
	then
	        WALL="nc $HOST $PORT"
	else
		echo "You must set HOST and PORT"
		exit -2
	fi
fi

while true
do
	$DIALOG --inputbox "`gettext \"Enter amount:\"`" 8 35 2> $FILE1 || end
	if cat $FILE1 | $WALL > $FILE2 2>$ERROR
	then
            	MSG="`gettext \"Sender:\"` `cat $FILE1`\\n\\n`gettext \"Continue?\"`"
            	$DIALOG --yesno "$MSG" 7 20 || end
            	MSG="`gettext \"Receiver:\"` `cat $FILE2`\\n\\n`gettext \"Continue?\"`"
            	$DIALOG --yesno "$MSG" 7 20 || end
		MSG="`gettext \"Amount:\"` `cat $FILE2`\\n\\n`gettext \"Continue?\"`"
		$DIALOG --yesno "$MSG" 7 20 || end
	else
		MSG="`gettext \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`gettext \"Continue?\"`"
		$DIALOG --yesno "$MSG" 10 35 || end
	fi
done
