#!/bin/sh
echo "Ethereum Wallet Transfer"

pfile="./passwd"
PASSWD=$(cat "$pfile")

#Displays account of the user
disp_account(){
echo "Your Wallet is:"
./geth --testnet --fast -exec "eth.accounts" attach 
}



#Unlock user account and send certain number of 'ether' 
send(){
SENDER=$1
RECEIVER=$2
AMOUNT=$3
./geth --exec "personal.unlockAccount('$SENDER', '$PASSWD')" attach > /dev/null
TRANSACTION=`./geth --testnet --fast -exec "eth.sendTransaction({from: '$SENDER', to: '$RECEIVER', value: web3.toWei('$AMOUNT', 'ether')})" attach`
echo $TRANSACTION
}


cli_main(){

if [ ! -z $1 ] && [ $1 = "-h" ];
    then
        #help
        exit
fi

#pulling variables from the UI script
if [ ! -z $1 ];
then	
		if [ $1 = "-a" ];
		then
			TRANSACTION="$(send $2 $3 $4)"
			echo $TRANSACTION
			exit
		fi
fi

while true
do
	printf "Please enter the account of SENDER:\n"
	read SENDER

	printf "Please enter the account of RECEIVER:\n"
	read RECEIVER

	printf "Please enter the AMOUNT of ethers:\n"
	read AMOUNT

	TRANSACTION="$(send $SENDER $RECEIVER $AMOUNT)"
	echo "Transaction code is:"
	echo $TRANSACTION
	exit

done

} 


cli_main $*
