#!/bin/sh

WALL=itmot
HOST=localhost
PORT=1234

SENDER=$1
RECEIVER=$2
AMOUNT=$3

FILE1=/tmp/wall1-$$
FILE2=/tmp/wall2-$$
ERROR=/tmp/wall-err-$$

GETTEXT="gettext -d itmo_ui"

if [ -r ~/.wall.conf ]
then
	. ~/.wall.conf
elif [ -r /etc/wall.conf ]
then
	. /etc/wall.conf
fi

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

help () {
        echo "Usage: $0 [ host [port] | --help ]"
}

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

if [ $# -eq 1 ]
then
        if [ $1 -eq '--help' ]
        then
                help
                exit -1
        else
                HOST=$1
        fi
elif [ $# -eq 2 ]
then
        PORT=$2
fi

if [ $# -ge 1 -o `basename $0` = 'itmo_ui' ]
then
	if [ $HOST -a $PORT ]
	then
	        WALL="nc $HOST $PORT"
	else
		echo "You must set HOST and PORT"
		exit -2
	fi
fi

while true
do
	$DIALOG --inputbox "`gettext \"Enter amount:\"`" 8 35 2> $FILE1 || end
	if cat $FILE1 | $WALL > $FILE2 2>$ERROR
	then
		MSG1="`gettext \"Sender:\"` `echo $SENDER`\\n\\n`gettext \"Continue?\"`"
		$DIALOG --yesno "$MSG1" 7 20 || end
		MSG2="`gettext \"Receiver:\"` `echo $RECEIVER`\\n\\n`gettext \"Continue?\"`"
		$DIALOG --yesno "$MSG2" 7 20 || end
		MSG3="`gettext \"Amount to transfer:\"` `cat $FILE2`\\n\\n`gettext \"Continue?\"`"
		$DIALOG --yesno "$MSG3" 7 20 || end

		TRANSACTION=$(./itmot -a $SENDER $RECEIVER $AMOUNT)
		echo $TRANSACTION
		MSG="`$GETTEXT \"Transaction ID is:\"`"
		MSG+="$TRANSACTION"
		$DIALOG --title "`$GETTEXT \"TRANSACTION number is:\"`" --msgbox "$TRANSACTION" 6 20
	else
		MSG="`gettext \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`gettext \"Continue?\"`"
		$DIALOG --yesno "$MSG" 10 35 || end
	fi
done
